const BOOTCAMP = {
  BOOTCAMP_GET_ALL_REQUEST: "BOOTCAMP_GET_ALL_REQUEST",
  BOOTCAMP_GET_ALL_SUCCESS: "BOOTCAMP_GET_ALL_SUCCESS",
  BOOTCAMP_GET_ALL_FAIL: "BOOTCAMP_GET_ALL_FAIL",
  BOOTCAMP_DETAILS_REQUEST: "BOOTCAMP_DETAILS_REQUEST",
  BOOTCAMP_DETAILS_SUCCESS: "BOOTCAMP_DETAILS_SUCCESS",
  BOOTCAMP_DETAILS_FAIL: "BOOTCAMP_DETAILS_FAIL",
};

export default BOOTCAMP;
