const COURSES = {
  GET_COURSE_BY_ID_REQUEST: "GET_COURSE_BY_ID_REQUEST",
  GET_COURSE_BY_ID_SUCCESS: "GET_COURSE_BY_ID_SUCCESS",
  GET_COURSE_BY_ID_FAIL: "GET_COURSE_BY_ID_FAIL",
};

export default COURSES;
